# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JXBWebKitProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JXBWebKitProject
  pod 'JXBWebKit', :path => '../'
  pod 'SSZipArchive'

  target 'JXBWebKitProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JXBWebKitProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
